title: CADRE-Cambridge Data Dictionary
description: learning how to create a static (but searchable) website for CADRE CCC
theme: just-the-docs

url: https://xd281.github.io/test-data-dictionary

aux_links:
  Template Repository: https://github.com/xd281/test-data-dictionary
