title: test web data dictionary CCC
description: learning how to create a static (but searchable) website for CADRE CCC
theme: just-the-docs

url: https://xd281.github.io/test-just-the-docs

aux_links:
  Template Repository: https://github.com/xd281/test-just-the-docs
